#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Stopping and removing service..." --weight=1
ynh_remove_systemd_config
yunohost service remove "$app" 2>/dev/null || true

ynh_remove_nginx_config
ynh_secure_remove --file="/var/log/$app"

ynh_script_progression --message="Removal complete!" --last
